sudo: required
services:
  - docker

before_install:
  - docker build -t atumu1025/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atumu1025/docker-react npm run test -- --coverage